# application-dev.yml
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/event_management_dev
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

    jpa:
      open-in-view: false
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true

  logging:
    level:
      com.eventmanagement: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
