# application-prod.yml
  spring:
    datasource:
      url: ${DATABASE_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: false

  logging:
    level:
      com.eventmanagement: INFO
      org.springframework.security: WARN
    file:
      name: logs/event-management.log

  jwt:
    secret: ${JWT_SECRET}